// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGE1zFYj0iqrVlpwRaXmzc0d03lPVxIro',
    appId: '1:61754267319:web:c369eb737207a9202edf32',
    messagingSenderId: '61754267319',
    projectId: 'fir-auth-task-2-84e3d',
    authDomain: 'fir-auth-task-2-84e3d.firebaseapp.com',
    storageBucket: 'fir-auth-task-2-84e3d.firebasestorage.app',
    measurementId: 'G-DQB1EYLRFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Hxdob6uJAtSj63r02FFdY4ygVQsrWPY',
    appId: '1:61754267319:android:e7d74682e851369e2edf32',
    messagingSenderId: '61754267319',
    projectId: 'fir-auth-task-2-84e3d',
    storageBucket: 'fir-auth-task-2-84e3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC8K95K4Y-3BjwquzGJ0rxpm9EdLXr2ec',
    appId: '1:61754267319:ios:3f52afb70abae20f2edf32',
    messagingSenderId: '61754267319',
    projectId: 'fir-auth-task-2-84e3d',
    storageBucket: 'fir-auth-task-2-84e3d.firebasestorage.app',
    iosBundleId: 'com.example.campusFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC8K95K4Y-3BjwquzGJ0rxpm9EdLXr2ec',
    appId: '1:61754267319:ios:3f52afb70abae20f2edf32',
    messagingSenderId: '61754267319',
    projectId: 'fir-auth-task-2-84e3d',
    storageBucket: 'fir-auth-task-2-84e3d.firebasestorage.app',
    iosBundleId: 'com.example.campusFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGE1zFYj0iqrVlpwRaXmzc0d03lPVxIro',
    appId: '1:61754267319:web:0c58e04dc641003a2edf32',
    messagingSenderId: '61754267319',
    projectId: 'fir-auth-task-2-84e3d',
    authDomain: 'fir-auth-task-2-84e3d.firebaseapp.com',
    storageBucket: 'fir-auth-task-2-84e3d.firebasestorage.app',
    measurementId: 'G-LT61DY0H0H',
  );
}
